function results = run_nparaxial_milestone_demos_yu()
%RUN_NPARAXIAL_MILESTONE_DEMOS_YU Run first-milestone demo checks.

    testFolder = fileparts(mfilename('fullpath'));
    rootFolder = fileparts(testFolder);
    addpath(fullfile(rootFolder, 'core'));
    addpath(testFolder);

    results = struct();
    results.single_thin_lens = demo_nparaxial_single_thin_lens_yu();
    results.two_thin_lens_match = demo_nparaxial_two_thin_lens_match_yu();
    results.two_surface_thick_lens = demo_nparaxial_two_surface_thick_lens_yu();
    results.dummy_identity = demo_nparaxial_dummy_identity_yu();
    results.strict_enabled = demo_nparaxial_strict_enabled_yu();
    results.same_z_event_order = demo_nparaxial_same_z_event_order_yu();
    results.csv_round_trip = demo_nparaxial_csv_round_trip_yu();
    results.mat_round_trip = demo_nparaxial_mat_round_trip_yu();
    results.check_prescription = demo_nparaxial_check_prescription_yu();
    results.default_prescriptions = demo_nparaxial_default_prescriptions_yu();

    disp('N-paraxial first-milestone demos passed.');
    fprintf('  %s: z_img = %.12g, m = %.12g\n', ...
        results.single_thin_lens.case_name, ...
        results.single_thin_lens.z_image, ...
        results.single_thin_lens.magnification);
    fprintf('  %s: z_img = %.12g, m = %.12g\n', ...
        results.two_thin_lens_match.case_name, ...
        results.two_thin_lens_match.z_image, ...
        results.two_thin_lens_match.magnification);
    fprintf('  %s: z_img = %.12g, m = %.12g\n', ...
        results.two_surface_thick_lens.case_name, ...
        results.two_surface_thick_lens.z_image, ...
        results.two_surface_thick_lens.magnification);
    fprintf('  %s: z_img = %.12g, m = %.12g\n', ...
        results.dummy_identity.case_name, ...
        results.dummy_identity.z_image, ...
        results.dummy_identity.magnification);
    fprintf('  %s: enabled rows = %d\n', ...
        results.strict_enabled.case_name, ...
        results.strict_enabled.num_enabled);
    fprintf('  %s: matrix difference = %.12g\n', ...
        results.same_z_event_order.case_name, ...
        results.same_z_event_order.matrix_difference);
    fprintf('  %s: rows = %d\n', ...
        results.csv_round_trip.case_name, ...
        results.csv_round_trip.rows);
    fprintf('  %s: rows = %d\n', ...
        results.mat_round_trip.case_name, ...
        results.mat_round_trip.rows);
    fprintf('  %s: invalid cases = %d\n', ...
        results.check_prescription.case_name, ...
        results.check_prescription.invalid_cases);
    fprintf('  %s: presets = %d\n', ...
        results.default_prescriptions.case_name, ...
        numel(results.default_prescriptions.presets));
end
