function results = run_nparaxial_milestone_demos_yu()
%RUN_NPARAXIAL_MILESTONE_DEMOS_YU Run first-milestone demo checks.

    testFolder = fileparts(mfilename('fullpath'));
    rootFolder = fileparts(testFolder);
    addpath(fullfile(rootFolder, 'core'));
    addpath(testFolder);

    results = struct();
    results.single_thin_lens = demo_nparaxial_single_thin_lens_yu();
    results.two_thin_lens_match = demo_nparaxial_two_thin_lens_match_yu();
    results.two_surface_thick_lens = demo_nparaxial_two_surface_thick_lens_yu();
    results.dummy_identity = demo_nparaxial_dummy_identity_yu();
    results.strict_enabled = demo_nparaxial_strict_enabled_yu();
    results.same_z_event_order = demo_nparaxial_same_z_event_order_yu();
    results.csv_round_trip = demo_nparaxial_csv_round_trip_yu();
    results.mat_round_trip = demo_nparaxial_mat_round_trip_yu();
    results.check_prescription = demo_nparaxial_check_prescription_yu();
    results.default_prescriptions = demo_nparaxial_default_prescriptions_yu();
    results.milestone2_diagnostics = demo_nparaxial_milestone2_diagnostics_yu();
    results.milestone22_exports = demo_nparaxial_milestone22_exports_yu();
    results.milestone221_stabilization = ...
        demo_nparaxial_milestone221_stabilization_yu();
    results.milestone222_vignetting = ...
        demo_nparaxial_milestone222_vignetting_yu();
    results.milestone223_matrix_chain = ...
        demo_nparaxial_milestone223_matrix_chain_yu();
    results.milestone231_ray_fan = ...
        demo_nparaxial_milestone231_ray_fan_yu();
    results.milestone233_paraxial_validity = ...
        demo_nparaxial_milestone233_paraxial_validity_yu();
    results.milestone2331_validity_stabilization = ...
        demo_nparaxial_milestone2331_validity_stabilization_yu();
    results.milestone234_surface_vertex_validity = ...
        demo_nparaxial_milestone234_surface_vertex_validity_yu();
    results.milestone2341_surface_vertex_stabilization = ...
        demo_nparaxial_milestone2341_surface_vertex_stabilization_yu();
    results.milestone235_true_intersection = ...
        demo_nparaxial_milestone235_true_intersection_yu();

    disp('N-paraxial first-milestone demos passed.');
    fprintf('  %s: z_img = %.12g, m = %.12g\n', ...
        results.single_thin_lens.case_name, ...
        results.single_thin_lens.z_image, ...
        results.single_thin_lens.magnification);
    fprintf('  %s: z_img = %.12g, m = %.12g\n', ...
        results.two_thin_lens_match.case_name, ...
        results.two_thin_lens_match.z_image, ...
        results.two_thin_lens_match.magnification);
    fprintf('  %s: z_img = %.12g, m = %.12g\n', ...
        results.two_surface_thick_lens.case_name, ...
        results.two_surface_thick_lens.z_image, ...
        results.two_surface_thick_lens.magnification);
    fprintf('  %s: z_img = %.12g, m = %.12g\n', ...
        results.dummy_identity.case_name, ...
        results.dummy_identity.z_image, ...
        results.dummy_identity.magnification);
    fprintf('  %s: enabled rows = %d\n', ...
        results.strict_enabled.case_name, ...
        results.strict_enabled.num_enabled);
    fprintf('  %s: matrix difference = %.12g\n', ...
        results.same_z_event_order.case_name, ...
        results.same_z_event_order.matrix_difference);
    fprintf('  %s: rows = %d\n', ...
        results.csv_round_trip.case_name, ...
        results.csv_round_trip.rows);
    fprintf('  %s: rows = %d\n', ...
        results.mat_round_trip.case_name, ...
        results.mat_round_trip.rows);
    fprintf('  %s: invalid cases = %d\n', ...
        results.check_prescription.case_name, ...
        results.check_prescription.invalid_cases);
    fprintf('  %s: presets = %d\n', ...
        results.default_prescriptions.case_name, ...
        numel(results.default_prescriptions.presets));
    fprintf('  %s: checks = %d\n', ...
        results.milestone2_diagnostics.case_name, ...
        results.milestone2_diagnostics.num_checks);
    fprintf('  %s: checks = %d\n', ...
        results.milestone22_exports.case_name, ...
        results.milestone22_exports.num_checks);
    fprintf('  %s: checks = %d, app smoke = %s\n', ...
        results.milestone221_stabilization.case_name, ...
        results.milestone221_stabilization.num_checks, ...
        results.milestone221_stabilization.app_smoke);
    fprintf('  %s: checks = %d, app vignetting smoke = %s\n', ...
        results.milestone222_vignetting.case_name, ...
        results.milestone222_vignetting.num_checks, ...
        results.milestone222_vignetting.app_vignetting_smoke);
    fprintf('  %s: checks = %d, app smoke = %s\n', ...
        results.milestone223_matrix_chain.case_name, ...
        results.milestone223_matrix_chain.num_checks, ...
        results.milestone223_matrix_chain.app_smoke);
    fprintf('  %s: checks = %d, app smoke = %s\n', ...
        results.milestone231_ray_fan.case_name, ...
        results.milestone231_ray_fan.num_checks, ...
        results.milestone231_ray_fan.app_smoke);
    fprintf('  %s: checks = %d, app smoke = %s\n', ...
        results.milestone233_paraxial_validity.case_name, ...
        results.milestone233_paraxial_validity.num_checks, ...
        results.milestone233_paraxial_validity.app_smoke);
    fprintf('  %s: checks = %d\n', ...
        results.milestone2331_validity_stabilization.case_name, ...
        results.milestone2331_validity_stabilization.num_checks);
    fprintf('  %s: checks = %d\n', ...
        results.milestone234_surface_vertex_validity.case_name, ...
        results.milestone234_surface_vertex_validity.num_checks);
    fprintf('  %s: checks = %d\n', ...
        results.milestone2341_surface_vertex_stabilization.case_name, ...
        results.milestone2341_surface_vertex_stabilization.num_checks);
    fprintf('  %s: checks = %d\n', ...
        results.milestone235_true_intersection.case_name, ...
        results.milestone235_true_intersection.num_checks);
end
