function cases = nparaxial_default_case_library_yu()
%NPARAXIAL_DEFAULT_CASE_LIBRARY_YU Structured classical default use cases.
%
% The case metadata separates object-at-infinity descriptions from the
% finite launch planes used by the paraxial trace engine.

    cases = make_case_local( ...
        "basic_single_lens_m_minus_0p5", ...
        "Single lens finite conjugate, m=-0.5", ...
        "Basic", ...
        "Finite-conjugate single thin lens with a 2:1 object/image distance ratio.", ...
        "finite", 0, 0, ...
        thin_lens_prescription_local("L1", 300, 100, 15), ...
        "Single field y", 0, -3, 3, 3, ...
        "Manual fixed-angle fan", 9, 0.035, "point", ...
        "Image at z=450 mm, magnification m=-0.5.", ...
        "Gaussian imaging: 1/f = 1/s + 1/s'.");

    cases(end+1) = make_case_local( ...
        "basic_single_lens_1to1", ...
        "Single lens 1:1 imaging", ...
        "Basic", ...
        "Single thin lens with object and image each at 2f.", ...
        "finite", 0, 0, ...
        thin_lens_prescription_local("L1", 200, 100, 15), ...
        "Single field y", 0, -3, 3, 3, ...
        "Manual fixed-angle fan", 9, 0.035, "point", ...
        "Image at z=400 mm, magnification m=-1.", ...
        "The symmetric 2f/2f layout gives unit absolute magnification.");

    cases(end+1) = make_case_local( ...
        "basic_single_lens_collimator", ...
        "Single lens collimator", ...
        "Basic", ...
        "Finite point source at the front focal plane of one thin lens.", ...
        "finite", 0, 0, ...
        make_prescription_local( ...
        ["L1"; "REF_OUT"], [1; 2], ...
        ["thinlens"; "dummy"], ...
        [100; 200], ...
        [15; Inf], ...
        [100; Inf], ...
        [Inf; Inf], ...
        [1; 1], [1; 1]), ...
        "Single field y", 0, -2, 2, 3, ...
        "Manual fixed-angle fan", 9, 0.035, "point", ...
        "Image at infinity; output rays are collimated.", ...
        "A point at the front focal plane launches a collimated output bundle.");

    cases(end+1) = make_case_local( ...
        "basic_single_focusing_lens_infinity", ...
        "Single focusing lens, object at infinity", ...
        "Basic", ...
        "Collimated input focused by a single thin lens.", ...
        "infinity", Inf, 0, ...
        thin_lens_prescription_local("L1", 100, 100, 15), ...
        "Y field sweep", 0, -6, 6, 7, ...
        "Manual fixed-angle fan", 7, 0.025, "collimated", ...
        "Collimated input focuses at z=200 mm.", ...
        "An object at infinity focuses at the back focal plane.");

    cases(end+1) = make_case_local( ...
        "relay_4f_1to1", ...
        "4f relay 1:1", ...
        "Relay", ...
        "Classical two-lens relay with equal focal lengths.", ...
        "finite", 0, 0, ...
        make_prescription_local( ...
        ["L1"; "STOP1"; "L2"], [1; 2; 3], ...
        ["thinlens"; "stop"; "thinlens"], [100; 200; 300], ...
        [18; 9; 18], [100; Inf; 100], [Inf; Inf; Inf], ...
        [1; 1; 1], [1; 1; 1]), ...
        "Single field y", 0, -3, 3, 3, ...
        "Manual fixed-angle fan", 9, 0.035, "point", ...
        "Image at z=400 mm, magnification m=-1.", ...
        "A 4f relay images with magnification -f2/f1.");

    cases(end+1) = make_case_local( ...
        "relay_4f_reducer_m_minus_0p5", ...
        "4f reducer, m=-0.5", ...
        "Relay", ...
        "Classical 4f relay with f2 half of f1.", ...
        "finite", 0, 0, ...
        make_prescription_local( ...
        ["L1"; "STOP1"; "L2"], [1; 2; 3], ...
        ["thinlens"; "stop"; "thinlens"], [100; 200; 250], ...
        [18; 9; 14], [100; Inf; 50], [Inf; Inf; Inf], ...
        [1; 1; 1], [1; 1; 1]), ...
        "Single field y", 0, -3, 3, 3, ...
        "Manual fixed-angle fan", 9, 0.035, "point", ...
        "Image at z=300 mm, magnification m=-0.5.", ...
        "The relay magnification follows -f2/f1.");

    cases(end+1) = make_case_local( ...
        "relay_4f_magnifier_m_minus_2", ...
        "4f magnifier, m=-2", ...
        "Relay", ...
        "Classical 4f relay with f2 twice f1.", ...
        "finite", 0, 0, ...
        make_prescription_local( ...
        ["L1"; "STOP1"; "L2"], [1; 2; 3], ...
        ["thinlens"; "stop"; "thinlens"], [50; 100; 200], ...
        [14; 8; 20], [50; Inf; 100], [Inf; Inf; Inf], ...
        [1; 1; 1], [1; 1; 1]), ...
        "Single field y", 0, -2, 2, 3, ...
        "Manual fixed-angle fan", 9, 0.035, "point", ...
        "Image at z=300 mm, magnification m=-2.", ...
        "Changing f2/f1 scales the relay magnification.");

    cases(end+1) = make_case_local( ...
        "afocal_keplerian_telescope", ...
        "Keplerian telescope", ...
        "Afocal", ...
        "Positive-positive telescope with lens spacing f1+f2.", ...
        "infinity", Inf, 0, ...
        make_prescription_local( ...
        ["L1"; "L2"; "REF_OUT"], [1; 2; 3], ...
        ["thinlens"; "thinlens"; "dummy"], ...
        [100; 250; 300], ...
        [18; 14; Inf], ...
        [100; 50; Inf], ...
        [Inf; Inf; Inf], ...
        [1; 1; 1], [1; 1; 1]), ...
        "Y field sweep", 0, -6, 6, 7, ...
        "Manual fixed-angle fan", 7, 0.02, "collimated", ...
        "Afocal C approximately 0; angular magnification about -2.", ...
        "A Keplerian telescope is afocal when the lens separation is f1+f2.");

    cases(end+1) = make_case_local( ...
        "afocal_galilean_telescope", ...
        "Galilean telescope", ...
        "Afocal", ...
        "Positive-negative telescope with lens spacing f1+f2.", ...
        "infinity", Inf, 0, ...
        make_prescription_local( ...
        ["L1"; "L2"; "REF_OUT"], [1; 2; 3], ...
        ["thinlens"; "thinlens"; "dummy"], ...
        [100; 150; 200], ...
        [18; 14; Inf], ...
        [100; -50; Inf], ...
        [Inf; Inf; Inf], ...
        [1; 1; 1], [1; 1; 1]), ...
        "Y field sweep", 0, -6, 6, 7, ...
        "Manual fixed-angle fan", 7, 0.02, "collimated", ...
        "Afocal C approximately 0; angular magnification about +2.", ...
        "A Galilean telescope uses a negative second lens for upright angular magnification.");
    
    cases(end+1) = make_case_local( ...
        "telecentric_object_space_1to1", ...
        "Object-space telecentric 1:1", ...
        "Telecentric", ...
        "Stop placed at the rear focal plane of a 1:1 imaging lens.", ...
        "finite", 0, 0, ...
        make_prescription_local( ...
        ["L1"; "STOP1"], [1; 2], ["thinlens"; "stop"], ...
        [200; 300], [18; 7], [100; Inf], [Inf; Inf], ...
        [1; 1], [1; 1]), ...
        "Single field y", 0, -3, 3, 3, ...
        "Manual fixed-angle fan", 9, 0.035, "point", ...
        "Image at z=400 mm with the stop at the rear focal plane.", ...
        "A rear-focal-plane stop places the entrance pupil at infinity.");

    cases(end+1) = make_case_local( ...
        "telecentric_image_space_1to1", ...
        "Image-space telecentric 1:1", ...
        "Telecentric", ...
        "Stop placed at the front focal plane of a 1:1 imaging lens.", ...
        "finite", 0, 0, ...
        make_prescription_local( ...
        ["STOP1"; "L1"], [1; 2], ["stop"; "thinlens"], ...
        [100; 200], [7; 18], [Inf; 100], [Inf; Inf], ...
        [1; 1], [1; 1]), ...
        "Single field y", 0, -3, 3, 3, ...
        "Manual fixed-angle fan", 9, 0.035, "point", ...
        "Image at z=400 mm with the stop at the front focal plane.", ...
        "A front-focal-plane stop places the exit pupil at infinity.");

    cases(end+1) = make_case_local( ...
        "telecentric_doubly_4f_m_minus_0p25", ...
        "Doubly telecentric 4f relay, m=-0.25", ...
        "Telecentric", ...
        "Two-lens 4f relay with the stop at the common focal plane.", ...
        "finite", 0, 0, ...
        make_prescription_local( ...
        ["L1"; "STOP1"; "L2"], [1; 2; 3], ...
        ["thinlens"; "stop"; "thinlens"], ...
        [200; 400; 450], ...
        [35; 10; 15], ...
        [200; Inf; 50], ...
        [Inf; Inf; Inf], ...
        [1; 1; 1], [1; 1; 1]), ...
        "Y field sweep", 0, -20, 20, 3, ...
        "Aperture-limited admitted cone", 9, 0.08, "point", ...
        "Image at z=500 mm, magnification m=-0.25; object-side and image-side telecentric.", ...
        "Doubly telecentric 4f relay: stop at common focal plane; magnification is -f2/f1.");

    cases(end+1) = make_case_local( ...
        "thick_biconvex", ...
        "Biconvex thick lens", ...
        "Thick", ...
        "Two refracting surfaces with finite center thickness.", ...
        "finite", 0, 0, ...
        make_prescription_local( ...
        ["S1"; "S2"], [1; 2], ["surface"; "surface"], ...
        [150; 160], [15; 15], [Inf; Inf], [80; -80], ...
        [1; 1.5], [1.5; 1]), ...
        "Single field y", 0, -2, 2, 3, ...
        "Manual fixed-angle fan", 9, 0.025, "point", ...
        "Finite-power thick lens with shifted principal planes.", ...
        "Surface matrices expose principal-plane shifts in a thick lens.");

    cases(end+1) = make_case_local( ...
        "thick_plano_convex", ...
        "Plano-convex thick lens", ...
        "Thick", ...
        "Finite-thickness plano-convex lens: curved first surface, plane second surface, and output reference plane.", ...
        "finite", 0, 0, ...
        make_prescription_local( ...
        ["S1"; "S2"; "REF_OUT"], [1; 2; 3], ...
        ["surface"; "surface"; "dummy"], ...
        [150; 160; 260], ...
        [18; 18; Inf], ...
        [Inf; Inf; Inf], ...
        [80; Inf; Inf], ...
        [1; 1.5; 1], [1.5; 1; 1]), ...
        "Single field y", 0, -2, 2, 3, ...
        "Manual fixed-angle fan", 9, 0.025, "point", ...
        "Positive-power plano-convex thick lens with output reference plane at z=260 mm.", ...
        "A plane interface uses R=Inf; the dummy plane is a non-powered output reference.");

    cases(end+1) = make_case_local( ...
        "thick_meniscus", ...
        "Meniscus thick lens", ...
        "Thick", ...
        "Finite-thickness weak positive meniscus lens with two same-sign radii and output reference plane.", ...
        "finite", 0, 0, ...
        make_prescription_local( ...
        ["S1"; "S2"; "REF_OUT"], [1; 2; 3], ...
        ["surface"; "surface"; "dummy"], ...
        [150; 160; 260], ...
        [18; 18; Inf], ...
        [Inf; Inf; Inf], ...
        [80; 160; Inf], ...
        [1; 1.5; 1], [1.5; 1; 1]), ...
        "Single field y", 0, -2, 2, 3, ...
        "Manual fixed-angle fan", 9, 0.025, "point", ...
        "Weak positive-power meniscus thick lens with output reference plane at z=260 mm.", ...
        "Same-sign radii illustrate radius sign convention; R2 larger than R1 gives weak positive net power.");

    cases(end+1) = make_case_local( ...
        "debug_legacy_two_thin_lens", ...
        "Legacy two-thin-lens", ...
        "Debug", ...
        "Shifted copy of the historical V2 two-thin-lens debug layout.", ...
        "finite", 0, 0, ...
        make_prescription_local( ...
        ["L1"; "STOP1"; "L2"], [1; 2; 3], ...
        ["thinlens"; "stop"; "thinlens"], [120; 220; 380], ...
        [75; 8; 95], [80; Inf; 70], [Inf; Inf; Inf], ...
        [1; 1; 1], [1; 1; 1]), ...
        "Single field y", 0, -4, 4, 3, ...
        "Manual fixed-angle fan", 9, 0.04, "point", ...
        "Legacy two-lens behavior preserved with object plane at z=0.", ...
        "Regression/debug case retained outside the main teaching defaults.");

    cases(end+1) = make_case_local( ...
        "debug_stop_clipping_demo", ...
        "Stop clipping demo", ...
        "Debug", ...
        "Shifted copy of the historical stop-clipping debug layout.", ...
        "finite", 0, 0, ...
        make_prescription_local( ...
        ["L1"; "STOP1"; "L2"; "D1"], [1; 2; 3; 4], ...
        ["thinlens"; "stop"; "thinlens"; "dummy"], ...
        [120; 200; 280; 310], [75; 5; 3; Inf], ...
        [80; Inf; 70; Inf], [Inf; Inf; Inf; Inf], ...
        [1; 1; 1; 1], [1; 1; 1; 1]), ...
        "Single field y", 0, -4, 4, 3, ...
        "Aperture-limited admitted cone", 9, 0.04, "point", ...
        "Small stop and second-lens aperture demonstrate clipping.", ...
        "Regression/debug case for aperture-stop and clipping behavior.");

    cases(end+1) = make_case_local( ...
        "debug_homogeneous_translation", ...
        "Homogeneous translation", ...
        "Debug", ...
        "Free-space propagation through a dummy event.", ...
        "finite", 0, 0, ...
        make_prescription_local( ...
        "D_TRANSLATE", 1, "dummy", 100, Inf, Inf, Inf, 1, 1), ...
        "Single field y", 1, -2, 2, 3, ...
        "Manual fixed-angle fan", 9, 0.035, "point", ...
        "No optical power; image remains at infinity for a point at z=0.", ...
        "Identity element for translation and redraw lifecycle checks.");

    for k = 1:numel(cases)
        cases(k).prescription = nparaxial_validate_prescription_yu( ...
            cases(k).prescription);
    end
end


function caseDef = make_case_local( ...
    key, name, family, description, objectConjugate, objectZ, launchZ, ...
    prescription, fieldMode, fieldY, fieldMinY, fieldMaxY, fieldCount, ...
    rayFanMode, nRays, uMax, sourceMode, expectedBehavior, teachingPoint)

    caseDef = struct();
    caseDef.name = string(name);
    caseDef.key = string(key);
    caseDef.family = string(family);
    caseDef.display_name = caseDef.family + " - " + caseDef.name;
    caseDef.description = string(description);
    caseDef.object_conjugate = string(objectConjugate);
    caseDef.object_z = double(objectZ);
    caseDef.launch_z = double(launchZ);
    caseDef.prescription = prescription;
    caseDef.field_mode = string(fieldMode);
    caseDef.field_y = double(fieldY);
    caseDef.field_min_y = double(fieldMinY);
    caseDef.field_max_y = double(fieldMaxY);
    caseDef.field_count = double(fieldCount);
    caseDef.ray_fan_mode = string(rayFanMode);
    caseDef.n_rays = double(nRays);
    caseDef.u_max = double(uMax);
    caseDef.source_mode = string(sourceMode);
    caseDef.expected_behavior = string(expectedBehavior);
    caseDef.teaching_point = string(teachingPoint);
    caseDef.field_angle_rad = 0;
    caseDef.enabled = true;
end


function prescription = thin_lens_prescription_local( ...
    elementId, z, focalLength, apertureRadius)

    prescription = make_prescription_local( ...
        elementId, 1, "thinlens", z, apertureRadius, focalLength, ...
        Inf, 1, 1);
end


function prescription = make_prescription_local( ...
    elementId, eventOrder, typeName, z, aperture, focalLength, radiusR, ...
    nBefore, nAfter)

    prescription = table;
    prescription.element_id = string(elementId(:));
    prescription.event_order = double(eventOrder(:));
    prescription.type = string(typeName(:));
    prescription.z = double(z(:));
    prescription.aperture_radius = double(aperture(:));
    prescription.focal_length = double(focalLength(:));
    prescription.radius_R = double(radiusR(:));
    prescription.n_before = double(nBefore(:));
    prescription.n_after = double(nAfter(:));
    prescription.enabled = true(height(prescription), 1);
end
