function T = nparaxial_phase_space_table_yu(chiefMarginalDiag)
%NPARAXIAL_PHASE_SPACE_TABLE_YU y-u and canonical y-p ray coordinates.

    bundle = chiefMarginalDiag.bundle;
    T = table( ...
        strings(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
        zeros(0, 1), zeros(0, 1), zeros(0, 1), false(0, 1), ...
        'VariableNames', { ...
        'ray_name', 'plane_index', 'z', 'y', 'u', 'n', 'p', 'traced'});

    for k = 1:numel(bundle)
        res = bundle(k).res;
        for q = 1:numel(res.z_hist)
            nMedium = res.n_hist(q);
            T(end+1, :) = { ...
                bundle(k).name, q, res.z_hist(q), res.y_hist(q), ...
                res.u_hist(q), nMedium, nMedium*res.u_hist(q), ...
                res.trc}; %#ok<AGROW>
        end
    end
end
