function prescription = nparaxial_default_prescription_yu(presetName)
%NPARAXIAL_DEFAULT_PRESCRIPTION_YU Default N-element paraxial prescription.
%
% With no input, this default reproduces the earlier two-thin-lens
% first-order layout: thin lens 1, internal aperture stop, thin lens 2.

    if nargin < 1 || strlength(string(presetName)) == 0
        presetName = "two thin lenses";
    end

    switch preset_key_local(presetName)
        case "singlethinlens"
            prescription = make_prescription_local( ...
                ["L1"], ...
                1, ...
                ["thinlens"], ...
                0, ...
                75, ...
                80, ...
                Inf, ...
                1, ...
                1);

        case "twothinlenses"
            prescription = make_prescription_local( ...
                ["L1"; "STOP"; "L2"], ...
                [1; 2; 3], ...
                ["thinlens"; "stop"; "thinlens"], ...
                [0; 100; 260], ...
                [75; 8; 95], ...
                [80; Inf; 70], ...
                [Inf; Inf; Inf], ...
                [1; 1; 1], ...
                [1; 1; 1]);

        case "twosurfacethicklens"
            prescription = make_prescription_local( ...
                ["S1"; "D1"; "S2"], ...
                [1; 2; 3], ...
                ["surface"; "dummy"; "surface"], ...
                [0; 8; 12], ...
                [30; Inf; 30], ...
                [Inf; Inf; Inf], ...
                [40; Inf; -40], ...
                [1; 1.5; 1.5], ...
                [1.5; 1.5; 1]);

        case "stopclippingdemo"
            prescription = make_prescription_local( ...
                ["L1"; "STOP"; "L2"; "D1"], ...
                [1; 2; 3; 4], ...
                ["thinlens"; "stop"; "thinlens"; "dummy"], ...
                [0; 80; 160; 190], ...
                [75; 5; 3; Inf], ...
                [80; Inf; 70; Inf], ...
                [Inf; Inf; Inf; Inf], ...
                [1; 1; 1; 1], ...
                [1; 1; 1; 1]);

        case "homogeneoustranslationfreespacepropagation"
            prescription = make_prescription_local( ...
                ["D_TRANSLATE"], ...
                1, ...
                ["dummy"], ...
                100, ...
                Inf, ...
                Inf, ...
                Inf, ...
                1, ...
                1);

        otherwise
            error(['Unknown default prescription "%s". Valid choices are ', ...
                'Single thin lens, Two thin lenses, Two-surface thick lens, ', ...
                'Stop clipping demo, and Homogeneous translation / ', ...
                'free-space propagation.'], string(presetName));
    end
end


function key = preset_key_local(presetName)
    key = lower(strtrim(string(presetName)));
    key = regexprep(key, '[^a-z0-9]', '');
end


function prescription = make_prescription_local( ...
    elementId, eventOrder, typeName, z, aperture, focalLength, radiusR, ...
    nBefore, nAfter)

    prescription = table;
    prescription.element_id = string(elementId(:));
    prescription.event_order = double(eventOrder(:));
    prescription.type = string(typeName(:));
    prescription.z = double(z(:));
    prescription.aperture_radius = double(aperture(:));
    prescription.focal_length = double(focalLength(:));
    prescription.radius_R = double(radiusR(:));
    prescription.n_before = double(nBefore(:));
    prescription.n_after = double(nAfter(:));
    prescription.enabled = true(height(prescription), 1);
end
